// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectUsers.Models;

namespace ProjectUsers.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190311195242_EFCoreCodeFirstSample.Models.MessagesContextAdded")]
    partial class EFCoreCodeFirstSampleModelsMessagesContextAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectUsers.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreationDate");

                    b.Property<string>("MessageBody");

                    b.Property<string>("RecipientName");

                    b.Property<string>("SenderName");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1L,
                            CreationDate = "11/03/19",
                            MessageBody = "Hello from the other side",
                            RecipientName = "Adnan Kardas",
                            SenderName = "Selma Kardas"
                        },
                        new
                        {
                            MessageId = 2L,
                            CreationDate = "11/03/19",
                            MessageBody = "Hello from the other side",
                            RecipientName = "Selma Kardas",
                            SenderName = "Adnan Kardas"
                        });
                });

            modelBuilder.Entity("ProjectUsers.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            Email = "selma.kardas@gmail.com",
                            UserName = "Selma Kardas"
                        },
                        new
                        {
                            UserId = 2L,
                            Email = "adnan.kardas@gmail.com",
                            UserName = "Adnan Kardas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
